// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4qowd6owBE3U6igyjXMmeh4fRMBnmUWM',
    appId: '1:401665690877:web:811bac043d1c6531d5c294',
    messagingSenderId: '401665690877',
    projectId: 'notifications-abb2f',
    authDomain: 'notifications-abb2f.firebaseapp.com',
    storageBucket: 'notifications-abb2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMQPxiq0UnsK41xU1bVgneJLn-Xe-HET0',
    appId: '1:401665690877:android:9eaa4eea87e31afad5c294',
    messagingSenderId: '401665690877',
    projectId: 'notifications-abb2f',
    storageBucket: 'notifications-abb2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGRvrTzuSzqSlzju4P_q0jgmjZty8DBw0',
    appId: '1:401665690877:ios:b4fc73d6f61441c8d5c294',
    messagingSenderId: '401665690877',
    projectId: 'notifications-abb2f',
    storageBucket: 'notifications-abb2f.appspot.com',
    iosBundleId: 'com.example.flutterNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGRvrTzuSzqSlzju4P_q0jgmjZty8DBw0',
    appId: '1:401665690877:ios:b4fc73d6f61441c8d5c294',
    messagingSenderId: '401665690877',
    projectId: 'notifications-abb2f',
    storageBucket: 'notifications-abb2f.appspot.com',
    iosBundleId: 'com.example.flutterNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4qowd6owBE3U6igyjXMmeh4fRMBnmUWM',
    appId: '1:401665690877:web:88fe28bf1939c235d5c294',
    messagingSenderId: '401665690877',
    projectId: 'notifications-abb2f',
    authDomain: 'notifications-abb2f.firebaseapp.com',
    storageBucket: 'notifications-abb2f.appspot.com',
  );
}
